services:
  proxy:
      image: nginx:alpine
      restart: always
      networks:
        proxynet:
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./config/proxy/cloudflare:/etc/proxy/cloudflare
        - ./config/proxy/conf.d:/etc/nginx/conf.d
        - ./config/proxy/tcpconf.d:/etc/nginx/tcpconf.d
        - ./config/proxy/nginx.conf:/etc/nginx/nginx.conf
        - ./data/proxy/ssl:/etc/nginx/ssl
        - ./config/proxy/options-ssl-nginx.conf:/etc/proxy/options-ssl-nginx.conf
        - ./config/proxy/ssl-dhparams:/etc/proxy/ssl-dhparams.pem
networks:
  proxynet:
    name: custom_network
